export type IntegrationStatus = 
  | 'ACTIVE_API'
  | 'ACTIVE_FEED'
  | 'REQUIRES_API_KEY'
  | 'REQUIRES_PARTNER_ACCESS'
  | 'AUTHORIZED_CRAWL'
  | 'UNAVAILABLE_BY_POLICY'
  | 'DEPRECATED';

export interface SourceDefinition {
  id: string;
  name: string;
  category: 
    | 'business_directory'
    | 'remote_jobs'
    | 'freelance'
    | 'tech_development'
    | 'ai_data_tasks'
    | 'writing'
    | 'design'
    | 'virtual_assistant'
    | 'customer_support'
    | 'transcription'
    | 'testing_research'
    | 'microtasks'
    | 'kenya_africa';
  integrationMethod: 'REST_API' | 'RSS_FEED' | 'JSON_FEED' | 'PARTNER_API' | 'MANUAL_PORTAL';
  status: IntegrationStatus;
  authRequirement: 'NONE' | 'API_KEY' | 'OAUTH2' | 'PARTNER_CONTRACT' | 'NONE_PUBLIC';
  geographicCoverage: 'WORLDWIDE' | 'AFRICA_KENYA' | 'US_NORTH_AMERICA' | 'EUROPE' | 'REGIONAL';
  supportedData: string[];
  attributionRequirements: string;
  termsSummary: string;
  websiteUrl: string;
  apiUrl?: string;
  notes: string;
}

export const SOURCE_REGISTRY: SourceDefinition[] = [
  // =========================================================================
  // 1. BUSINESS DIRECTORIES & GEODATA
  // =========================================================================
  {
    id: 'osm_overpass',
    name: 'OpenStreetMap Overpass API',
    category: 'business_directory',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Business Name', 'Category', 'Address', 'Phone', 'Coordinates', 'Tags'],
    attributionRequirements: 'OpenStreetMap contributors under ODbL license',
    termsSummary: 'Free global geodata with reasonable rate limits and cached requests.',
    websiteUrl: 'https://www.openstreetmap.org',
    apiUrl: 'https://overpass-api.de/api/interpreter',
    notes: 'Primary zero-key global business discovery engine with Nominatim geocoding.',
  },
  {
    id: 'google_places',
    name: 'Google Places API (New)',
    category: 'business_directory',
    integrationMethod: 'REST_API',
    status: 'REQUIRES_API_KEY',
    authRequirement: 'API_KEY',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Business Name', 'Phone', 'Address', 'Rating', 'Review Count', 'Website Uri'],
    attributionRequirements: 'Google Maps Platform Attribution',
    termsSummary: 'Commercial Places API; requires GOOGLE_PLACES_API_KEY in server environment.',
    websiteUrl: 'https://developers.google.com/maps/documentation/places/web-service',
    apiUrl: 'https://places.googleapis.com/v1/places:searchText',
    notes: 'Enabled automatically when GOOGLE_PLACES_API_KEY is configured in .env.',
  },
  {
    id: 'yelp_fusion',
    name: 'Yelp Fusion API',
    category: 'business_directory',
    integrationMethod: 'REST_API',
    status: 'REQUIRES_API_KEY',
    authRequirement: 'API_KEY',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Business Name', 'Phone', 'Address', 'Rating', 'Review Count', 'Categories'],
    attributionRequirements: 'Yelp Branding and Attribution Guidelines',
    termsSummary: 'Free tier up to 5,000 requests/day with API Key.',
    websiteUrl: 'https://www.yelp.com/developers',
    apiUrl: 'https://api.yelp.com/v3/businesses/search',
    notes: 'Enabled automatically when YELP_API_KEY is configured in .env.',
  },
  {
    id: 'foursquare_places',
    name: 'Foursquare Places API',
    category: 'business_directory',
    integrationMethod: 'REST_API',
    status: 'REQUIRES_API_KEY',
    authRequirement: 'API_KEY',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Place Name', 'Address', 'Phone', 'Categories', 'Coordinates'],
    attributionRequirements: 'Powered by Foursquare',
    termsSummary: 'Requires Developer Account and FOURSQUARE_API_KEY.',
    websiteUrl: 'https://location.foursquare.com/developer/',
    apiUrl: 'https://api.foursquare.com/v3/places/search',
    notes: 'Enabled automatically when FOURSQUARE_API_KEY is configured in .env.',
  },

  // =========================================================================
  // 2. REMOTE JOBS & GLOBAL MARKETPLACES
  // =========================================================================
  {
    id: 'remotive',
    name: 'Remotive Public Jobs API',
    category: 'remote_jobs',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Job Title', 'Company', 'Category', 'Tags', 'Candidate Location', 'Apply URL', 'Salary'],
    attributionRequirements: 'Powered by Remotive Public API',
    termsSummary: 'Free public developer endpoint without authentication; cached per hour.',
    websiteUrl: 'https://remotive.com',
    apiUrl: 'https://remotive.com/api/remote-jobs',
    notes: 'High reliability worldwide remote opportunities across software, support, writing, design, and marketing.',
  },
  {
    id: 'arbeitnow',
    name: 'Arbeitnow Job Board API',
    category: 'remote_jobs',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Job Title', 'Company Name', 'Location', 'Remote Status', 'Tags', 'Apply URL'],
    attributionRequirements: 'Jobs provided by Arbeitnow API',
    termsSummary: 'Official free public JSON API for tech and remote employment.',
    websiteUrl: 'https://www.arbeitnow.com',
    apiUrl: 'https://www.arbeitnow.com/api/job-board-api',
    notes: 'Active worldwide and European tech opportunities with visa and remote tags.',
  },
  {
    id: 'himalayas',
    name: 'Himalayas Remote Jobs API',
    category: 'remote_jobs',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Job Title', 'Company Name', 'Category', 'Seniority', 'Compensation', 'Location Restrictions', 'Apply URL'],
    attributionRequirements: 'Source: Himalayas App',
    termsSummary: 'Free public JSON endpoint for verified remote employers.',
    websiteUrl: 'https://himalayas.app',
    apiUrl: 'https://himalayas.app/jobs/api',
    notes: 'Deep company metadata and transparent salary brackets for remote roles.',
  },
  {
    id: 'weworkremotely',
    name: 'We Work Remotely Public Feeds',
    category: 'remote_jobs',
    integrationMethod: 'RSS_FEED',
    status: 'ACTIVE_FEED',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Job Title', 'Company', 'Category', 'Description', 'Apply URL', 'PubDate'],
    attributionRequirements: 'We Work Remotely Public RSS',
    termsSummary: 'Public RSS feed distributed by We Work Remotely for syndication.',
    websiteUrl: 'https://weworkremotely.com',
    apiUrl: 'https://weworkremotely.com/categories/remote-programming-jobs.rss',
    notes: 'Leading remote community with dedicated engineering, design, customer support, and writing feeds.',
  },
  {
    id: 'jobspresso',
    name: 'Jobspresso Remote Feed',
    category: 'remote_jobs',
    integrationMethod: 'RSS_FEED',
    status: 'ACTIVE_FEED',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Job Title', 'Company', 'Apply Link', 'Snippet', 'Published Date'],
    attributionRequirements: 'Jobspresso Syndication Feed',
    termsSummary: 'Publicly syndicated job listings feed.',
    websiteUrl: 'https://jobspresso.co',
    apiUrl: 'https://jobspresso.co/feed/',
    notes: 'Curated remote opportunities in tech, marketing, customer support, and product.',
  },
  {
    id: 'remoteok',
    name: 'Remote OK Public API',
    category: 'remote_jobs',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Job Title', 'Company', 'Tags', 'Location', 'Apply URL', 'Date'],
    attributionRequirements: 'Remote OK API',
    termsSummary: 'Official public JSON API; rate-limited and cached.',
    websiteUrl: 'https://remoteok.com',
    apiUrl: 'https://remoteok.com/api',
    notes: 'Worldwide developer, AI, design, and writing gigs.',
  },
  {
    id: 'jobicy',
    name: 'Jobicy Remote Jobs API',
    category: 'remote_jobs',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Job Title', 'Company Name', 'Company Logo', 'Salary Min/Max', 'Geo', 'Industry', 'Job Type', 'Apply URL'],
    attributionRequirements: 'Jobs provided by Jobicy Remote Jobs API',
    termsSummary: 'Official public API v2 and syndicated RSS feed for remote tech, design, marketing, and management opportunities.',
    websiteUrl: 'https://jobicy.com',
    apiUrl: 'https://jobicy.com/api/v2/remote-jobs',
    notes: 'Zero-key worldwide remote opportunities with structured salary brackets and automated RSS fallback.',
  },
  {
    id: 'themuse',
    name: 'The Muse Jobs API',
    category: 'remote_jobs',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Job Title', 'Company Name', 'Locations', 'Categories', 'Levels', 'Apply URL'],
    attributionRequirements: 'Powered by The Muse API',
    termsSummary: 'Free unauthenticated public developer endpoint for verified, curated company roles.',
    websiteUrl: 'https://www.themuse.com',
    apiUrl: 'https://www.themuse.com/api/public/jobs',
    notes: 'Curated corporate and remote opportunities from verified tech and innovative employers.',
  },
  {
    id: 'workingnomads',
    name: 'Working Nomads Remote Community',
    category: 'remote_jobs',
    integrationMethod: 'MANUAL_PORTAL',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Curated Remote Roles', 'Design', 'Development', 'Management'],
    attributionRequirements: 'Working Nomads',
    termsSummary: 'Portal utilizes client-side search application; automated crawling or scraping prohibited by ToS.',
    websiteUrl: 'https://www.workingnomads.com',
    notes: 'Enterprise or affiliate partner integration required for structured data syndication.',
  },
  {
    id: 'wellfound',
    name: 'Wellfound (formerly AngelList Talent)',
    category: 'tech_development',
    integrationMethod: 'PARTNER_API',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'OAUTH2',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Startup Opportunities', 'Equity Grants', 'Founding Engineer Roles'],
    attributionRequirements: 'Wellfound, Inc.',
    termsSummary: 'No public unauthenticated API; access requires approved recruiter/partner OAuth2 credentials. Automated web scraping strictly barred by robots.txt and ToS.',
    websiteUrl: 'https://wellfound.com',
    notes: 'Requires Wellfound Recruiter Partner Agreement.',
  },
  {
    id: 'career_nest',
    name: 'Career Nest',
    category: 'remote_jobs',
    integrationMethod: 'MANUAL_PORTAL',
    status: 'UNAVAILABLE_BY_POLICY',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Job Search Portal'],
    attributionRequirements: 'Career Nest',
    termsSummary: 'Closed career website without public developer APIs or machine-readable feeds.',
    websiteUrl: 'https://careernest.com',
    notes: 'No authorized developer integration available.',
  },
  {
    id: 'un_careers',
    name: 'UN Careers (United Nations Inspira)',
    category: 'remote_jobs',
    integrationMethod: 'MANUAL_PORTAL',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['International Civil Service Roles', 'Consultancies', 'Volunteer Postings'],
    attributionRequirements: 'United Nations Secretariat',
    termsSummary: 'Managed via the official Inspira talent management system; open public search API not provided.',
    websiteUrl: 'https://careers.un.org',
    notes: 'Requires direct portal navigation or institutional data agreement.',
  },
  {
    id: 'devpost',
    name: 'Devpost Hackathons & Bounties',
    category: 'tech_development',
    integrationMethod: 'PARTNER_API',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'API_KEY',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Virtual Hackathons', 'Prizes & Bounties', 'Coding Competitions'],
    attributionRequirements: 'Devpost, Inc.',
    termsSummary: 'Public web feeds are protected behind Cloudflare anti-bot verification. Official integration requires Devpost API partner agreement.',
    websiteUrl: 'https://devpost.com',
    notes: 'Virtual hackathon challenges and tech bounties.',
  },
  {
    id: 'kaggle',
    name: 'Kaggle Competitions & Community Tasks',
    category: 'ai_data_tasks',
    integrationMethod: 'REST_API',
    status: 'REQUIRES_API_KEY',
    authRequirement: 'API_KEY',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['ML Competitions', 'Prize Pools', 'Dataset Challenges'],
    attributionRequirements: 'Kaggle / Google LLC',
    termsSummary: 'Requires official Kaggle API credentials (kaggle.json with username and key).',
    websiteUrl: 'https://www.kaggle.com',
    apiUrl: 'https://www.kaggle.com/api/v1',
    notes: 'Competitions and machine learning benchmarks; activated via Kaggle API credentials.',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn Talent Solutions',
    category: 'remote_jobs',
    integrationMethod: 'PARTNER_API',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Global Job Postings', 'Company Profiles', 'Skill Requirements'],
    attributionRequirements: 'LinkedIn Corporation',
    termsSummary: 'Strict anti-scraping policy enforced via robots.txt and automated bot detection. Official job discovery requires LinkedIn Enterprise Partner API contract.',
    websiteUrl: 'https://www.linkedin.com',
    notes: 'Enterprise partner agreement required; unauthorized crawling strictly forbidden.',
  },
  {
    id: 'indeed',
    name: 'Indeed Hiring Platform',
    category: 'remote_jobs',
    integrationMethod: 'PARTNER_API',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Aggregated Job Postings', 'Salary Estimates'],
    attributionRequirements: 'Indeed, Inc.',
    termsSummary: 'Legacy Publisher API is sunsetted. Access to Indeed Job Search API requires an approved Indeed Technology Partner agreement.',
    websiteUrl: 'https://www.indeed.com',
    notes: 'Technology Partner contract required; automated scraping prohibited.',
  },
  {
    id: 'flexjobs',
    name: 'FlexJobs Curated Remote Careers',
    category: 'remote_jobs',
    integrationMethod: 'MANUAL_PORTAL',
    status: 'UNAVAILABLE_BY_POLICY',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Vetted Remote & Flexible Jobs'],
    attributionRequirements: 'FlexJobs Corporation',
    termsSummary: 'Subscription paywall service; closed ecosystem with no open public developer API.',
    websiteUrl: 'https://www.flexjobs.com',
    notes: 'Paywalled platform; direct member access only.',
  },

  // =========================================================================
  // 3. KENYA & AFRICA OPPORTUNITIES
  // =========================================================================
  {
    id: 'africa_jobs_adapter',
    name: 'Africa & Kenya Remote Discovery Adapter',
    category: 'kenya_africa',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'AFRICA_KENYA',
    supportedData: ['Job Title', 'Company', 'Region', 'Country (Kenya/Nigeria/SA)', 'Category', 'Apply Link'],
    attributionRequirements: 'Public African Remote Aggregations',
    termsSummary: 'Verified public African remote and tech opportunities.',
    websiteUrl: 'https://webhunt-delta.vercel.app',
    notes: 'Dedicated filter returning remote and regional positions tailored for Kenyan and African professionals.',
  },
  {
    id: 'fuzu',
    name: 'Fuzu Career Portal',
    category: 'kenya_africa',
    integrationMethod: 'MANUAL_PORTAL',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'AFRICA_KENYA',
    supportedData: ['East African Career Listings'],
    attributionRequirements: 'Fuzu Ltd.',
    termsSummary: 'No public unauthenticated REST API available; requires formal employer/enterprise partner API agreement.',
    websiteUrl: 'https://www.fuzu.com',
    notes: 'Enterprise partner integration pending API authorization.',
  },
  {
    id: 'brightermonday',
    name: 'BrighterMonday Kenya',
    category: 'kenya_africa',
    integrationMethod: 'MANUAL_PORTAL',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'AFRICA_KENYA',
    supportedData: ['Kenyan & East African Job Postings'],
    attributionRequirements: 'BrighterMonday / The African Talent Company',
    termsSummary: 'Requires recruiter partner API credentials; public automated scraping prohibited by ToS.',
    websiteUrl: 'https://www.brightermonday.co.ke',
    notes: 'Partner API tier required.',
  },

  // =========================================================================
  // 4. FREELANCING & TALENT PLATFORMS
  // =========================================================================
  {
    id: 'upwork',
    name: 'Upwork Global Inc.',
    category: 'freelance',
    integrationMethod: 'PARTNER_API',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'OAUTH2',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Freelance Contracts', 'Milestones', 'Job Posts'],
    attributionRequirements: 'Upwork API Terms of Use',
    termsSummary: 'Requires approved Upwork Developer Account and OAuth2 client credentials. Scraping is strictly forbidden by robots.txt and ToS.',
    websiteUrl: 'https://www.upwork.com',
    apiUrl: 'https://developers.upwork.com/',
    notes: 'Direct API key activation supported via enterprise partner program.',
  },
  {
    id: 'fiverr',
    name: 'Fiverr International',
    category: 'freelance',
    integrationMethod: 'PARTNER_API',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'OAUTH2',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Gigs', 'Custom Offers'],
    attributionRequirements: 'Fiverr API Terms',
    termsSummary: 'No public open job feed. Requires certified affiliate or enterprise developer partner token.',
    websiteUrl: 'https://www.fiverr.com',
    notes: 'Requires Fiverr Partner Key.',
  },
  {
    id: 'freelancer_com',
    name: 'Freelancer.com API',
    category: 'freelance',
    integrationMethod: 'REST_API',
    status: 'REQUIRES_API_KEY',
    authRequirement: 'OAUTH2',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Projects', 'Bids', 'Contests'],
    attributionRequirements: 'Freelancer API Agreement',
    termsSummary: 'Requires Freelancer OAuth token to query project search endpoints.',
    websiteUrl: 'https://www.freelancer.com/api',
    notes: 'OAuth2 integration available with developer token.',
  },

  // =========================================================================
  // 5. AI TRAINING, DATA ANNOTATION & MACHINE LEARNING PLATFORMS
  // =========================================================================
  {
    id: 'clickworker',
    name: 'Clickworker AI Community',
    category: 'ai_data_tasks',
    integrationMethod: 'MANUAL_PORTAL',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['AI Training Tasks', 'Data Annotation', 'Text Classification', 'Image Categorization', 'Search Relevance', 'Data Collection'],
    attributionRequirements: 'Clickworker GmbH',
    termsSummary: 'Customer API is restricted to ordering tasks; worker tasks require worker portal registration and qualification tests. No open public job-search API.',
    websiteUrl: 'https://www.clickworker.com',
    notes: 'Direct applicant onboarding portal with qualification testing. Integrated via verified platform catalog.',
  },
  {
    id: 'crowdgen_appen',
    name: 'CrowdGen / Appen',
    category: 'ai_data_tasks',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['AI Training', 'Search Engine Evaluation', 'Speech & Language Data', 'Translation', 'Transcription', 'ML Evaluation'],
    attributionRequirements: 'Appen / CrowdGen',
    termsSummary: 'Official unauthenticated Lever public postings API for contractor positions plus CrowdGen portal for project-based tasks.',
    websiteUrl: 'https://crowdgen.com',
    apiUrl: 'https://api.lever.co/v0/postings/appen',
    notes: 'Live global contractor and linguist listings queried via Lever ATS endpoint; verified project acceptance requirements.',
  },
  {
    id: 'telus_digital_ai',
    name: 'TELUS Digital AI Community',
    category: 'ai_data_tasks',
    integrationMethod: 'MANUAL_PORTAL',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['AI Data Evaluation', 'Search Relevance', 'Language Evaluation', 'Image & Text Annotation', 'AI QA Tasks'],
    attributionRequirements: 'TELUS Digital (formerly TELUS International)',
    termsSummary: 'Ground Truth Studio APIs are client-facing for annotation pipelines. Contributor roles are managed via the official AI Community portal with strict country/language restrictions.',
    websiteUrl: 'https://www.telusdigital.com',
    apiUrl: 'https://www.telusinternational.ai',
    notes: 'Official AI Community portal onboarding with explicit language and country eligibility verification.',
  },
  {
    id: 'oneforma',
    name: 'OneForma by Centific',
    category: 'ai_data_tasks',
    integrationMethod: 'MANUAL_PORTAL',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['AI Data Collection', 'Speech Recording', 'Transcription', 'Translation', 'Search Evaluation', 'LLM Datasets'],
    attributionRequirements: 'Centific / OneForma',
    termsSummary: 'Contribute platform tasks are gated behind worker login, NDA, and language pair certifications. No public unauthenticated search API.',
    websiteUrl: 'https://www.oneforma.com',
    notes: 'Project opportunities catalog with original direct application URLs preserved.',
  },
  {
    id: 'dataannotation_tech',
    name: 'DataAnnotation.tech',
    category: 'ai_data_tasks',
    integrationMethod: 'MANUAL_PORTAL',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['AI Response Evaluation', 'Writing & Reasoning Tasks', 'Coding Evaluation', 'Mathematics Evaluation', 'RLHF'],
    attributionRequirements: 'DataAnnotation Tech',
    termsSummary: 'Worker onboarding requires rigorous initial assessment; no public search API or job feed. Zero fabricated earnings or eligibility claims.',
    websiteUrl: 'https://www.dataannotation.tech',
    notes: 'Verified portal link with country restriction and skill assessment indicators.',
  },
  {
    id: 'outlier_ai',
    name: 'Outlier.ai / Scale AI',
    category: 'ai_data_tasks',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['AI Response Evaluation', 'Coding Tasks', 'Mathematics Tasks', 'Writing Tasks', 'Expert-Domain AI Training', 'RLHF'],
    attributionRequirements: 'Scale AI / Outlier.ai',
    termsSummary: 'Official public Greenhouse ATS endpoint from parent Scale AI with live roles, combined with Outlier direct onboarding portal.',
    websiteUrl: 'https://outlier.ai',
    apiUrl: 'https://boards-api.greenhouse.io/v1/boards/scaleai/jobs',
    notes: 'Direct unauthenticated ATS queries for live opportunities + verified applicant portal.',
  },
  {
    id: 'toloka_ai',
    name: 'Toloka AI / Mindrift',
    category: 'ai_data_tasks',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Data Labeling', 'Image Annotation', 'Text Classification', 'Search Relevance', 'AI Evaluation', 'AI Tutors'],
    attributionRequirements: 'Toloka AI',
    termsSummary: 'Official unauthenticated Greenhouse ATS endpoint for remote contractor and AI tutor roles; crowd microtasks managed in Toloka app.',
    websiteUrl: 'https://toloka.ai',
    apiUrl: 'https://boards-api.greenhouse.io/v1/boards/toloka/jobs',
    notes: 'Public contractor opportunities queried via Greenhouse; preserved original application URLs.',
  },
  {
    id: 'remotasks',
    name: 'Remotasks (Scale AI)',
    category: 'ai_data_tasks',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Image Annotation', 'LiDAR Annotation', 'Data Labeling', 'Computer Vision Tasks'],
    attributionRequirements: 'Scale AI / Remotasks',
    termsSummary: 'Remotasks operations have officially transitioned into Outlier.ai. Legacy board tracked via Greenhouse endpoint.',
    websiteUrl: 'https://www.remotasks.com',
    apiUrl: 'https://boards-api.greenhouse.io/v1/boards/remotasks/jobs',
    notes: 'Official migration notice to Outlier.ai documented; location restrictions clearly reflected.',
  },
  {
    id: 'alignerr',
    name: 'Alignerr by Labelbox',
    category: 'ai_data_tasks',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['AI Model Evaluation', 'Expert Feedback', 'Coding Evaluation', 'Language Tasks', 'Mathematics Evaluation'],
    attributionRequirements: 'Labelbox / Alignerr',
    termsSummary: 'Official unauthenticated Greenhouse ATS endpoint from parent Labelbox + Alignerr expert contributor portal with assessment requirement.',
    websiteUrl: 'https://www.alignerr.com',
    apiUrl: 'https://boards-api.greenhouse.io/v1/boards/labelbox/jobs',
    notes: 'Queries live expert roles on Greenhouse; direct platform onboarding at alignerr.com.',
  },
  {
    id: 'rws_trainai',
    name: 'RWS TrainAI',
    category: 'ai_data_tasks',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['AI Data Collection', 'Language Evaluation', 'Translation', 'Search Evaluation', 'Speech & Language Datasets'],
    attributionRequirements: 'RWS Group',
    termsSummary: 'Official unauthenticated Lever public postings API with live AI dataset, translation, and annotation roles.',
    websiteUrl: 'https://www.rws.com',
    apiUrl: 'https://api.lever.co/v0/postings/rws',
    notes: 'Live linguist, data annotator, and AI quality specialist vacancies with strict country & language requirements.',
  },
  {
    id: 'welocalize',
    name: 'Welocalize AI & Search Rating',
    category: 'ai_data_tasks',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['AI Data Evaluation', 'Search Quality Rating', 'Language Data', 'Translation', 'Localization', 'Speech Evaluation'],
    attributionRequirements: 'Welocalize, Inc.',
    termsSummary: 'Official unauthenticated Lever public postings API (weloglobal) for Search Quality Raters, AI Content Evaluators, and Localization specialists.',
    websiteUrl: 'https://www.welocalize.com',
    apiUrl: 'https://api.lever.co/v0/postings/weloglobal',
    notes: 'Real live Search Quality Rater and AI evaluator opportunities with original apply links preserved.',
  },
  {
    id: 'prolific',
    name: 'Prolific Academic Research & Data Tasks',
    category: 'ai_data_tasks',
    integrationMethod: 'REST_API',
    status: 'REQUIRES_API_KEY',
    authRequirement: 'API_KEY',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Scientific Studies', 'AI Feedback Tasks'],
    attributionRequirements: 'Prolific API',
    termsSummary: 'Requires researcher or participant API key.',
    websiteUrl: 'https://www.prolific.com',
    notes: 'Researcher API available for verified partner accounts.',
  },

  // =========================================================================
  // 6. WRITING, DESIGN, CUSTOMER SUPPORT, TRANSCRIPTION, TESTING, MICROTASKS
  // =========================================================================
  {
    id: 'problogger',
    name: 'ProBlogger Job Board',
    category: 'writing',
    integrationMethod: 'RSS_FEED',
    status: 'ACTIVE_FEED',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Content Writing', 'Copywriting', 'SEO Articles', 'Apply Link'],
    attributionRequirements: 'ProBlogger Jobs RSS',
    termsSummary: 'Public RSS feed syndicating freelance and remote writing roles.',
    websiteUrl: 'https://problogger.com/jobs/',
    apiUrl: 'https://problogger.com/jobs/feed/',
    notes: 'Curated writing opportunities aggregated into writing category.',
  },
  {
    id: 'dribbble_jobs',
    name: 'Dribbble Design Opportunities',
    category: 'design',
    integrationMethod: 'REST_API',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'API_KEY',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['UI/UX Design', 'Brand Identity', 'Product Design'],
    attributionRequirements: 'Dribbble Holdings',
    termsSummary: 'Requires Dribbble Enterprise/Partner API.',
    websiteUrl: 'https://dribbble.com/jobs',
    notes: 'Remote design opportunities queried through Remotive & Himalayas design endpoints.',
  },
  {
    id: 'usertesting',
    name: 'UserTesting / User Interviews',
    category: 'testing_research',
    integrationMethod: 'MANUAL_PORTAL',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Usability Testing', 'Product Feedback Sessions'],
    attributionRequirements: 'UserTesting, Inc.',
    termsSummary: 'Closed participant panel; direct sign-up via authenticated platform.',
    websiteUrl: 'https://www.usertesting.com',
    notes: 'Direct application link routed through verified source catalog.',
  },
  {
    id: 'rev_transcription',
    name: 'Rev / TranscribeMe',
    category: 'transcription',
    integrationMethod: 'MANUAL_PORTAL',
    status: 'REQUIRES_PARTNER_ACCESS',
    authRequirement: 'PARTNER_CONTRACT',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Audio Transcription', 'Captioning', 'Translation'],
    attributionRequirements: 'Rev.com, Inc.',
    termsSummary: 'Freelancer application portal with transcription skill test.',
    websiteUrl: 'https://www.rev.com/freelancers',
    notes: 'Direct verified onboarding catalog link.',
  },

  // =========================================================================
  // 7. EXPANDED SEARCH & DIRECT ATS INTEGRATIONS
  // =========================================================================
  {
    id: 'adzuna',
    name: 'Adzuna Global Job Search API',
    category: 'remote_jobs',
    integrationMethod: 'REST_API',
    status: (process.env.ADZUNA_APP_ID && process.env.ADZUNA_APP_KEY) ? 'ACTIVE_API' : 'REQUIRES_API_KEY',
    authRequirement: 'API_KEY',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Job Title', 'Company Name', 'Salary Min/Max', 'Location', 'Redirect URL', 'Category'],
    attributionRequirements: 'Powered by Adzuna Job Search API',
    termsSummary: 'Requires ADZUNA_APP_ID and ADZUNA_APP_KEY in server environment. Gracefully skips when unconfigured.',
    websiteUrl: 'https://developer.adzuna.com',
    apiUrl: 'https://api.adzuna.com/v1/api/jobs',
    notes: 'Global multi-country search index with verified salary estimates and location breakdown.',
  },
  {
    id: 'jooble',
    name: 'Jooble Search API',
    category: 'remote_jobs',
    integrationMethod: 'REST_API',
    status: process.env.JOOBLE_API_KEY ? 'ACTIVE_API' : 'REQUIRES_API_KEY',
    authRequirement: 'API_KEY',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Job Title', 'Company', 'Salary', 'Location', 'Job Snippet', 'Apply Link'],
    attributionRequirements: 'Jobs from Jooble',
    termsSummary: 'Requires JOOBLE_API_KEY in server environment. Gracefully skips when unconfigured.',
    websiteUrl: 'https://jooble.org/api/about',
    apiUrl: 'https://jooble.org/api/',
    notes: 'Aggregates millions of jobs globally with keywords, salary filters, and location tags.',
  },
  {
    id: 'usajobs',
    name: 'USAJobs Official Search API',
    category: 'remote_jobs',
    integrationMethod: 'REST_API',
    status: (process.env.USAJOBS_API_KEY && process.env.USAJOBS_USER_AGENT) ? 'ACTIVE_API' : 'REQUIRES_API_KEY',
    authRequirement: 'API_KEY',
    geographicCoverage: 'US_NORTH_AMERICA',
    supportedData: ['Job Title', 'Department', 'Pay Grade / Salary', 'Remote Status', 'Apply URI'],
    attributionRequirements: 'Data provided by USAJOBS.gov',
    termsSummary: 'Requires USAJOBS_API_KEY and USAJOBS_USER_AGENT headers. Public government API with verified salaries.',
    websiteUrl: 'https://developer.usajobs.gov',
    apiUrl: 'https://data.usajobs.gov/api/search',
    notes: 'Verified remote and telework federal postings with strict salary disclosures.',
  },
  {
    id: 'ats_provider',
    name: 'Direct Employer ATS (Greenhouse, Lever, Ashby)',
    category: 'tech_development',
    integrationMethod: 'REST_API',
    status: 'ACTIVE_API',
    authRequirement: 'NONE_PUBLIC',
    geographicCoverage: 'WORLDWIDE',
    supportedData: ['Direct Job Postings', 'Department', 'Location Restrictions', 'Application URL', 'Company Metadata'],
    attributionRequirements: 'Direct Employer Career Boards via ATS APIs',
    termsSummary: 'Direct unauthenticated public job board endpoints from top tech employers (Canonical, Gitlab, Automattic, Spotify, Linear, OpenAI, Ramp).',
    websiteUrl: 'https://greenhouse.io',
    notes: 'Zero-intermediary verified listings queried directly from employer ATS job boards with 0 API keys required.',
  },
];

export function getSourcesByCategory(category: string): SourceDefinition[] {
  if (category === 'all') return SOURCE_REGISTRY;
  return SOURCE_REGISTRY.filter((s) => s.category === category);
}

export function getActiveProvidersSummary() {
  const activeApis = SOURCE_REGISTRY.filter((s) => s.status === 'ACTIVE_API' || s.status === 'ACTIVE_FEED');
  const partnerApis = SOURCE_REGISTRY.filter((s) => s.status === 'REQUIRES_PARTNER_ACCESS' || s.status === 'REQUIRES_API_KEY');
  return {
    totalRegistered: SOURCE_REGISTRY.length,
    activeLive: activeApis.length,
    requiresKeyOrPartner: partnerApis.length,
    sources: SOURCE_REGISTRY,
  };
}

